/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Framecifrario.java
 *
 * Created on 10-mag-2011, 16.21.13
 */

package CifrarioCesare;

import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author raffaele
 */
public class Framecifrario extends javax.swing.JFrame {

    /** Creates new form Framecifrario */
    public Framecifrario() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selezionaFiles = new javax.swing.JFileChooser();
        etichettaStatus = new javax.swing.JLabel();
        anteprima = new javax.swing.JButton();
        decripta = new javax.swing.JButton();
        testoAnteprima = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        testoDecript = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        apriFiles = new javax.swing.JMenuItem();
        salvaFiles = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        etichettaStatus.setText("Pronto");

        anteprima.setText("Anteprima(+)");
        anteprima.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteprimaActionPerformed(evt);
            }
        });

        decripta.setText("Decript!");
        decripta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decriptaActionPerformed(evt);
            }
        });

        testoAnteprima.setEditable(false);

        testoDecript.setColumns(20);
        testoDecript.setEditable(false);
        testoDecript.setRows(5);
        jScrollPane1.setViewportView(testoDecript);

        jButton1.setText("Anteprima(-)");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jMenu1.setText("File");

        apriFiles.setText("Apri");
        apriFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apriFilesActionPerformed(evt);
            }
        });
        jMenu1.add(apriFiles);

        salvaFiles.setText("Salva");
        salvaFiles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaFilesActionPerformed(evt);
            }
        });
        jMenu1.add(salvaFiles);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(etichettaStatus)
                .addContainerGap(361, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(decripta, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(anteprima, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(testoAnteprima, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)))
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(anteprima)
                        .addGap(2, 2, 2)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(testoAnteprima, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(decripta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addComponent(etichettaStatus))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apriFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apriFilesActionPerformed
         if(selezionaFiles.showOpenDialog(this) == selezionaFiles.APPROVE_OPTION){
            input = selezionaFiles.getSelectedFile();
            BufferedReader lettoreBuffer = null;
            FileReader lettoreFile = null;
            try {
                lettoreFile = new FileReader(input);
                lettoreBuffer = new BufferedReader(lettoreFile);
                primaRiga = lettoreBuffer.readLine();
                if(primaRiga == null) throw new IOException("File Vuoto"); 
                    
            } 
            catch (FileNotFoundException ex) {etichettaStatus.setText("File Non Trovato!");
                                              input = null;
            }
            catch (IOException e) {etichettaStatus.setText("Errore"+e.getMessage());
                                    input = null;
            }
            finally{
                testoAnteprima.setText(primaRiga);
                if(lettoreBuffer != null)
                    try {
                    lettoreBuffer.close();
                } catch (IOException ex) {ex.printStackTrace();

                }
             if(lettoreFile != null)
                    try {
                    lettoreFile.close();
                } catch (IOException ex) {ex.printStackTrace();

                }
            }
         etichettaStatus.setText("File Aperto");
         chiave = 0;
         }


    }//GEN-LAST:event_apriFilesActionPerformed

    private void anteprimaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteprimaActionPerformed
        if(primaRiga != null)
            chiave++;
        antePrima();
    }//GEN-LAST:event_anteprimaActionPerformed

    private void decriptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decriptaActionPerformed
        if(input != null){
            BufferedReader lettoreBuffer = null;
            try {
                String temp;
                lettoreBuffer = new BufferedReader(new FileReader(input));
                testoDecript.setText("");
                try {
                    while ((temp = lettoreBuffer.readLine()) != null) {

                        testoDecript.append(traduciRiga(temp) + "\n");
                    }
                } catch (IOException ex) {
                    Logger.getLogger(Framecifrario.class.getName()).log(Level.SEVERE, null, ex);
                }


            }
            catch (FileNotFoundException ex) {etichettaStatus.setText("File Non Trovato!");
                                              input = null;}
        }
    }//GEN-LAST:event_decriptaActionPerformed

    private void salvaFilesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaFilesActionPerformed
        if(!testoDecript.getText().equals(""))
            if(selezionaFiles.showSaveDialog(this) == selezionaFiles.APPROVE_OPTION){
                File output;
                output = selezionaFiles.getSelectedFile();
                PrintWriter printScrivi = null;
            try {
                printScrivi = new PrintWriter(new FileWriter(output), true);
                printScrivi.print(testoDecript.getText());
                etichettaStatus.setText("Salvataggio effettuato");
            } catch (IOException ex) { etichettaStatus.setText("");}
            finally{
                if(printScrivi != null)
                    printScrivi.close();

            }



            }






    }//GEN-LAST:event_salvaFilesActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         if(primaRiga != null)
            chiave--;
        antePrima();



    }//GEN-LAST:event_jButton1ActionPerformed

    private void antePrima(){
       if(primaRiga != null)
                testoAnteprima.setText(traduciRiga(primaRiga));
    }

    private String traduciRiga(String s){
        String output = "";
        int lettera ;
        for(int i = 0; i < s.length();i++ ){
            lettera = s.charAt(i);
            if(lettera >= vala && lettera <= valz)
                lettera = (lettera - vala + chiave + 26)%26+vala;
            if(lettera >= valA && lettera <= valZ)
                lettera = (lettera - valA + chiave + 26)%26+valA;
        output = output+(char)lettera;
       }
       return output;
   }
    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Framecifrario().setVisible(true);
            }
        });
    }
    File input;
    String primaRiga = null;
    int chiave = 0;
    private final int vala = 'a', valA = 'A', valz = 'z' , valZ = 'Z';
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton anteprima;
    private javax.swing.JMenuItem apriFiles;
    private javax.swing.JButton decripta;
    private javax.swing.JLabel etichettaStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem salvaFiles;
    private javax.swing.JFileChooser selezionaFiles;
    private javax.swing.JTextField testoAnteprima;
    private javax.swing.JTextArea testoDecript;
    // End of variables declaration//GEN-END:variables

}
