/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PannelloColorato.java
 *
 * Created on 3-mag-2011, 16.44.45
 */

package PannelloColorato;

import java.awt.Color;

/**
 *
 * @author raffaele
 */
public class PannelloColorato extends javax.swing.JFrame {

    /** Creates new form PannelloColorato */
    public PannelloColorato() {
        initComponents();
        //Pannello.setBackground(Color.BLUE);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Pannello = new javax.swing.JPanel();
        tastoColore1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Pannello.setBackground(Color.RED);

        tastoColore1.setText("Cambia Colore");
        tastoColore1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tastoColore1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PannelloLayout = new javax.swing.GroupLayout(Pannello);
        Pannello.setLayout(PannelloLayout);
        PannelloLayout.setHorizontalGroup(
            PannelloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelloLayout.createSequentialGroup()
                .addGap(123, 123, 123)
                .addComponent(tastoColore1)
                .addContainerGap(147, Short.MAX_VALUE))
        );
        PannelloLayout.setVerticalGroup(
            PannelloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PannelloLayout.createSequentialGroup()
                .addGap(121, 121, 121)
                .addComponent(tastoColore1)
                .addContainerGap(126, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pannello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Pannello, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tastoColore1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tastoColore1ActionPerformed
            // TODO add your handling code here:
        if(Pannello.getBackground().equals(Color.RED))
            Pannello.setBackground(Color.WHITE);
        else
            Pannello.setBackground(Color.RED);
    }//GEN-LAST:event_tastoColore1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PannelloColorato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Pannello;
    private javax.swing.JButton tastoColore1;
    // End of variables declaration//GEN-END:variables

}
