/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PositivoNegativo.java
 *
 * Created on 3-mag-2011, 17.10.27
 */

/**
 *
 * @author raffaele
 */
public class PositivoNegativo extends javax.swing.JFrame {

    /** Creates new form PositivoNegativo */
    public PositivoNegativo() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        matteBorder1 = new javax.swing.border.MatteBorder(null);
        campoTesto = new javax.swing.JTextField();
        checkSign = new javax.swing.JButton();
        etichettaSegno = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Controllo Segno v0.1");
        setAlwaysOnTop(true);
        setBounds(new java.awt.Rectangle(50, 50, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        getContentPane().setLayout(new java.awt.GridLayout(1, 3));

        campoTesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoTestoActionPerformed(evt);
            }
        });
        getContentPane().add(campoTesto);

        checkSign.setText("Check Sign");
        checkSign.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkSignActionPerformed(evt);
            }
        });
        getContentPane().add(checkSign);

        etichettaSegno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        etichettaSegno.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(etichettaSegno);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void campoTestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoTestoActionPerformed
       String risultato = "";
       try{
       if(Double.valueOf(campoTesto.getText()) >= 0)
           risultato = "POSITIVO!!";
       else
            risultato = "NEGATIVO!!";
       }catch(NumberFormatException e){
            risultato = "CAZZO SCRIVI!";
       }
       finally{
           etichettaSegno.setText(risultato);
       }
       


    }//GEN-LAST:event_campoTestoActionPerformed

    private void checkSignActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkSignActionPerformed
       campoTestoActionPerformed(null);
    }//GEN-LAST:event_checkSignActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PositivoNegativo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoTesto;
    private javax.swing.JButton checkSign;
    private javax.swing.JLabel etichettaSegno;
    private javax.swing.border.MatteBorder matteBorder1;
    // End of variables declaration//GEN-END:variables

}
