/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrameApriFile.java
 *
 * Created on 18-mag-2011, 16.54.02
 */

package esercizio142;

import java.io.*;

/**
 *
 * @author raffaele

 *
14.2 Si definisca una applicazione grafica costituita da una finestra che contiene (in questo ordine):
un campo di testo e un bottone
cliccando sul bottone deve avvenire:
• viene aperto il file (come file di testo) il cui nome è contenuto nel campo di testo.
• Si scrive nel file la frase:
“Il nome di questo file e’ lungo: “ seguita dalla lunghezza del nome del file
Se il campo di testo è vuoto non avverrà nulla

 */
public class FrameApriFile extends javax.swing.JFrame {

    /** Creates new form FrameApriFile */
    public FrameApriFile() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        apriFile = new javax.swing.JButton();
        campoTesto = new javax.swing.JTextField();
        labelStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        apriFile.setText("Apri");
        apriFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                apriFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(apriFile, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(campoTesto, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apriFile)
                    .addComponent(campoTesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(labelStatus))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void apriFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_apriFileActionPerformed
        if(!campoTesto.getText().equals("")){
            String nomeFile = campoTesto.getText();
            int numLettere = nomeFile.length();
            String temp = "";
            BufferedReader lettoreFile = null;
            try {
                String contenutoFile = "";
                lettoreFile = new BufferedReader(new FileReader(nomeFile));
                while ((temp = lettoreFile.readLine()) != null) {
                    contenutoFile += temp + "\n";
                }
                temp = "il nome di questo file è lungo "+numLettere+"\n"+contenutoFile;
                BufferedWriter scriviFile = new BufferedWriter(new FileWriter(nomeFile));
                scriviFile.write(temp);
                scriviFile.flush();
                labelStatus.setText("File aperto e modificato");
            }catch (FileNotFoundException ex) {
                labelStatus.setText("File non trovato");
            }
            catch (IOException ex) {
                labelStatus.setText("Errore: "+ex.getStackTrace());
            }
        }
        else
            labelStatus.setText("Se non scrivi niente non faccio niente");
    }//GEN-LAST:event_apriFileActionPerformed






    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameApriFile().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apriFile;
    private javax.swing.JTextField campoTesto;
    private javax.swing.JLabel labelStatus;
    // End of variables declaration//GEN-END:variables

}
